### ISSUE TITLE
cargo version fails to parse with `0.18.0`

### ISSUE THREAD

**Issue by gdhgdhgdh** [JetBrains/teamcity-rust-plugin#35]
In recent releases of cargo, there is now a hyphen `-` between the word `cargo` and the version number...

previously:

`cargo 0.17.0-nightly (71e996e 2017-01-02)`

now

`cargo-0.18.0-nightly (a73a665 2017-02-14)`

leading to this error on startup, and the Cargo runner being unavailable to use because `Cargo_Path` is not set, and all Cargo runner jobs depend on that. This test case was on OS X, tho I don't expect it will be limited to just that OS.

```
jvm 1    | [2017-03-03 09:10:31,726]   WARN - rver.rust.AbstractToolProvider - Failed to parse Cargo version: null: Unexpected character 'LETTER(c)' at position '0', expecting '[DIGIT]' (enable debug to see stacktrace)  
```

**Comment by dtretyakov** [comment]
Ok, thanks for reporting.

**Comment by dtretyakov** [comment]
It seems that in the latest toolchain it was reverted, but anyway it was fixed:

```
>rustup run nightly cargo --version
cargo 0.18.0-nightly (5db6d64 2017-03-03)
```
