### ISSUE TITLE
Support test arguments

### ISSUE THREAD

**Issue by LukeMauldin** [JetBrains/teamcity-rust-plugin#47]
Plugin needs to support test arugments.  Example: `cargo test foo -- --test-threads 1`.  There is no way from the Teamcity plugin to pass `--test-threads 1` in the `cargo test` template.

**Comment by missingdays** [comment]
@LukeMauldin there is `Arguments` field for `test` command. You can provide such arguments there, for example `-- --test-threads 1`.

Does that help your case?

**Comment by LukeMauldin** [comment]
I have switched away from using the Rust language for now so I will close this issue. Thank you.
