### ISSUE TITLE
Unmet requirements: Cargo_Path exists on Windows

### ISSUE THREAD

**Issue by soulflyman** [JetBrains/teamcity-rust-plugin#54]
I installed rust with the help of rustup on Windows 10.
I can use cargo and rustc from every where in the system (cmd, powershell, visual studio code...).

But when I create a build project in TeamCity for a rust application I get the following Error in the Agent Summary:
> Unmet requirements: Cargo_Path exists 

Don't know what Cargo_Path should look like. I'm only aware of CARGO_HOME and RUSTUP_HOME.

Path of cargo.exe:
```powershell
[teamcity.zz.local]: PS C:\> where.exe cargo
C:\Users\xy\.cargo\bin\cargo.exe
```

Version information:
TeamCity: TeamCity Professional 2021.2.3 (build 99711)
Agent: Installt as Windows service (Version 99711)
teamcity-rust-plugin: Version 0.6.0

Installed rust tool chain versions:
```powershell
[teamcity.zz.local]: PS C:\> rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
[teamcity.zz.local]: PS C:\> cargo --version
cargo 1.59.0 (49d8809dc 2022-02-10)
[teamcity.zz.local]: PS C:\> rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

Environment variables are set to
```powershell
[teamcity.zz.local]: PS C:\> echo $Env:CARGO_HOME
C:\Users\xy\.cargo
[teamcity.zz.local]: PS C:\> echo $Env:RUSTUP_HOME
C:\Users\xy\.rustup
[teamcity.spadom.local]: PS C:\> echo $env:path
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin;C:\Users\xy\.cargo\bin;C:\Users\xy\AppData\Local\Microsoft\WindowsApps;C:\Users\xy\.dotnet\tools
```

Here the log of the last agent startup: [teamcity-agent.log](https://github.com/JetBrains/teamcity-rust-plugin/files/8288058/teamcity-agent.log)
Importen parts are:
```
[2022-03-17 16:45:24,872]   INFO - rver.rust.AbstractToolProvider - Locating Cargo tool
[2022-03-17 16:45:24,887]   INFO - rver.rust.AbstractToolProvider - Locating Rustc tool
[2022-03-17 16:45:24,903]   INFO - rver.rust.AbstractToolProvider - Locating Rustup tool
```
And thats it, no message that cargo was found or not.

What am I missing, how can I tell my agent to build rust code?

Don't know but maybe this is realated to #53 🤷

**Comment by missingdays** [comment]
@soulflyman hi

That means the agent wasn't able to find `cargo` executable. If it was found, you'd see `Found Cargo at ...` message. I will look into that

As a workaround, you could use `rustup` to install the Rust for you, maybe the agent will be able to detect it then.

**Comment by soulflyman** [comment]
Hi, I did install the rust tool chain with the help of rustup... 😞  Or do you mean I should use rustup inside a build step of the build configuration?

**Comment by missingdays** [comment]
Yes, I mean use `rustup` in the build step

**Comment by missingdays** [comment]
@soulflyman We've tried to reproduce on clean Windows installation, installing Rust using `rustup`, and `cargo` was detected correctly on the agent.

Are you maybe using different Windows user for the agent? Perhaps it doesn't have `cargo` installed, or doesn't have sufficient permissions to use it?

**Comment by soulflyman** [comment]
I think it was indeed a permission problem. I've started from scratch and set CARGO_HOME to c:\tools\.cargo and RUSTUP_HOME  to  c:\tools\.rustup. Allowed acces for everyone to this folders. And installed rust with rustup again.
It woked without any problems.
Thank you for hinting me into  the right direction.
